### ISSUE TITLE
Labels not defined

### ISSUE THREAD

**Issue by SpyrosMouselinos** [arthurfortes/speech2text_keras#1]
Hello my friend, i think you have forgotten a cell or a block of code at the start of your notebook.
What exactly are the labels you are looping over @2nd cell?

**Comment by helloerikaaa** [comment]
Anyone knowing something about the labels? 
I tried using an array with all the audio labels but I get`ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type numpy.ndarray).` when `train_test_split`

**Comment by arthurfortes** [comment]
Hi @SpyrosMouselinos! The labels are the name of classes that you want to use. For example:

```
# All samples
labels = [
    'left', 'cat', 'wow', 'six', 'go', 'one', 'dog', 'nine', 'sheila', 'yes',
    'down', 'bird', 'tree', 'up', 'eight', 'bed', 'three', 'on', 'house',
    'five', 'seven', 'zero', 'right', 'four', 'no', 'two', 'off', 'happy',
    'stop', 'marvin'
]

# Subsample
labels = [
    'left', 'go', 'yes', 'down', 'up', 'on', 'right', 'no', 'off', 'stop',
] 
```

I will fix the notebook with this cell. Thanks!

**Comment by arthurfortes** [comment]
I added a new cell in the notebook with labels
